### PR TITLE
Initial release of RPM and Deb packaging files

### PR DESCRIPTION
**Pull request by paulhopkins**
These are the packaging files based on a release version 0.1. Please check carefully before accepting request.

### CODE REVIEW

**Comment by skymoo** [comment]
The packaging scripts look good to me however the manifest hasn't been updated so the packaging isn't included in the distribution tarball so that makes testing more difficult.

**Comment by paulhopkins** [comment]
I have added the packaging files into the `MANIFEST.in` list and also fixed a couple of issues with the Debian packaging.

**Comment by skymoo** [comment]
When I try and build a SRPM in order to run a test build with mock it complains:

```
$ git tag v0.1
$ python setup.py sdist
running sdist
running egg_info
creating ligo_dot_org.egg-info
writing requirements to ligo_dot_org.egg-info/requires.txt
writing ligo_dot_org.egg-info/PKG-INFO
writing namespace_packages to ligo_dot_org.egg-info/namespace_packages.txt
writing top-level names to ligo_dot_org.egg-info/top_level.txt
writing dependency_links to ligo_dot_org.egg-info/dependency_links.txt
writing manifest file 'ligo_dot_org.egg-info/SOURCES.txt'
reading manifest file 'ligo_dot_org.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ligo_dot_org.egg-info/SOURCES.txt'
running check
creating ligo-dot-org-0.1
creating ligo-dot-org-0.1/debian
creating ligo-dot-org-0.1/debian/source
creating ligo-dot-org-0.1/ligo
creating ligo-dot-org-0.1/ligo/org
creating ligo-dot-org-0.1/ligo_dot_org.egg-info
copying files to ligo-dot-org-0.1...
copying LICENSE -> ligo-dot-org-0.1
copying MANIFEST.in -> ligo-dot-org-0.1
copying README.md -> ligo-dot-org-0.1
copying ligo.org.spec -> ligo-dot-org-0.1
copying setup.cfg -> ligo-dot-org-0.1
copying setup.py -> ligo-dot-org-0.1
copying versioneer.py -> ligo-dot-org-0.1
copying debian/changelog -> ligo-dot-org-0.1/debian
copying debian/compat -> ligo-dot-org-0.1/debian
copying debian/control -> ligo-dot-org-0.1/debian
copying debian/copyright -> ligo-dot-org-0.1/debian
copying debian/rules -> ligo-dot-org-0.1/debian
copying debian/source/format -> ligo-dot-org-0.1/debian/source
copying ligo/__init__.py -> ligo-dot-org-0.1/ligo
copying ligo/org/__init__.py -> ligo-dot-org-0.1/ligo/org
copying ligo/org/_version.py -> ligo-dot-org-0.1/ligo/org
copying ligo/org/ecp.py -> ligo-dot-org-0.1/ligo/org
copying ligo/org/kerberos.py -> ligo-dot-org-0.1/ligo/org
copying ligo_dot_org.egg-info/PKG-INFO -> ligo-dot-org-0.1/ligo_dot_org.egg-info
copying ligo_dot_org.egg-info/SOURCES.txt -> ligo-dot-org-0.1/ligo_dot_org.egg-info
copying ligo_dot_org.egg-info/dependency_links.txt -> ligo-dot-org-0.1/ligo_dot_org.egg-info
copying ligo_dot_org.egg-info/namespace_packages.txt -> ligo-dot-org-0.1/ligo_dot_org.egg-info
copying ligo_dot_org.egg-info/requires.txt -> ligo-dot-org-0.1/ligo_dot_org.egg-info
copying ligo_dot_org.egg-info/top_level.txt -> ligo-dot-org-0.1/ligo_dot_org.egg-info
Writing ligo-dot-org-0.1/setup.cfg
UPDATING ligo-dot-org-0.1/ligo/org/_version.py
set ligo-dot-org-0.1/ligo/org/_version.py to '0.1'
creating dist
Creating tar archive
removing 'ligo-dot-org-0.1' (and everything under it)
$ rpmbuild -ts ligo-dot-org-0.1.tar.gz
error: File /home/adam.mercer/ligo.org-0.1.tar.gz: No such file or directory
$
```

Looks like the problem is that the tarball uses the name `ligo-dot-org` but the spec file has `ligo.org`. The name of the tarball and the name of the package listed in the spec file needs to be consistent.

**Comment by paulhopkins** [comment]
To make it work I have renamed the spec file _and_ the package to `ligo-dot-org`, which is what is specified in the `setup.py` file. I have also renamed the Debian package to be consistent.

**Comment by skymoo** [comment]
I was able to build SL7 RPMs, uploaded to:
https://ldas-jobs.cgca.uwm.edu/~ram/ligo.org-0.1/

**Comment by duncanmmacleod** [comment]
This was subsumed into #11.

**Pull request closed without merging**
